version: '3'

services:

  # React JS Website
  web:
    build: views/diguisepperecipes.com
    volumes:
      - './views/diguisepperecipes.com:/app'
      - '/app/node_modules'
    expose:
      - '3000'
    environment:
      - NODE_ENV=development
    networks:
      - development-network

  # Apollo GraphQL Gateway
  graphql:
    build: services/graphql-gateway
    volumes:
      - './services/graphql-gateway:/app'
      - '/app/node_modules'
    depends_on:
      - recipe_graphql
    ports:
      - '4000:4000'
    expose:
      - '4000'
    networks:
      - development-network

  # Recipe GraphQL Micro-Service
  recipe_graphql:
    build: services/recipe-graphql-service
    volumes:
      - './services/recipe-graphql-service:/app'
      - '/app/node_modules'
    ports:
      - '4001:4001'
    expose:
      - '4001'
    networks:
      - development-network

  # recipe_table:
  #   image: amazon/dynamodb-local:latest
  #   ports:
  #     - '8000:8080'
  #   expose:
  #     - 8000
  #   networks:
  #     - development-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: development_nginx
    depends_on:
      - web
      - graphql
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - development-network
    # logging:
    #   driver: none

  # elasticsearch:
  #   image:  docker.elastic.co/elasticsearch/elasticsearch:7.1.1
  #   container_name: elasticsearch
  #   environment:
  #     - cluster.name=recipes-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.zen.ping.unicast.hosts=elasticsearch"
  #   expose:
  #     - '9200'
  #   ports:
  #     - '9200:9200'
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   networks:
  #     - development-network

networks: 
  development-network:

# volumes:
#   esdata:
#     driver: local
