version: '3'

services:

  # React JS Website
  web:
    build: views/diguisepperecipes.com
    ports:
      - "3000:3000"
    volumes:
      - './views/diguisepperecipes.com:/app'
      - '/app/node_modules'
    # ports:
    #   - '3000:3000'
    expose:
      - '3000'
    environment:
      - NODE_ENV=development
    networks:
      - development-network

  nginx:
    image: nginx:latest
    container_name: development_nginx
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - development-network

  # TODO: some sort of data store.

networks: 
  development-network: